// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef convert_h
#define convert_h
#include <FL/Fl.H>
int main();
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class ConvertirUI {
public:
  ConvertirUI();
  Fl_Input *inputHpa;
  Fl_Output *outputInHg;
  Fl_Button *calcButton;
private:
  inline void cb_calcButton_i(Fl_Button*, void*);
  static void cb_calcButton(Fl_Button*, void*);
public:
  Fl_Button *clearButton;
private:
  inline void cb_clearButton_i(Fl_Button*, void*);
  static void cb_clearButton(Fl_Button*, void*);
public:
  void limpiar();
  double hpaToInHg(const double &hpa, double &inHg);
  void convertir();
};
#endif
